# Generated by Django 5.2.5 on 2026-01-20 03:09

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nivel_jerarquico', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='ConfiguracionNomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio_vigencia', models.IntegerField(help_text='Año de vigencia de estos valores', unique=True)),
                ('salario_minimo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('auxilio_transporte', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'verbose_name': 'Configuración de Nómina',
                'verbose_name_plural': 'Configuraciones de Nómina',
            },
        ),
        migrations.CreateModel(
            name='Gerencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('TI', 'Tarjeta de Identidad'), ('PAS', 'Pasaporte'), ('PEP', 'Permiso Especial de Permanencia'), ('PPT', 'Permiso por Protección Temporal'), ('OTRO', 'Otro')], default='CC', max_length=10)),
                ('cedula', models.CharField(max_length=20, unique=True, verbose_name='Número de Documento')),
                ('primer_apellido', models.CharField(max_length=50)),
                ('segundo_apellido', models.CharField(blank=True, max_length=50, null=True)),
                ('primer_nombre', models.CharField(max_length=50)),
                ('segundo_nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('fecha_nacimiento', models.DateField()),
                ('nacionalidad', models.CharField(default='Colombiana', max_length=50)),
                ('estado_civil', models.CharField(choices=[('SOLTERO', 'Soltero(a)'), ('CASADO', 'Casado(a)'), ('UNION_LIBRE', 'Unión Libre'), ('SEPARADO', 'Separado(a)'), ('DIVORCIADO', 'Divorciado(a)'), ('VIUDO', 'Viudo(a)')], default='SOLTERO', max_length=20)),
                ('direccion', models.CharField(max_length=200)),
                ('departamento', models.CharField(max_length=100)),
                ('municipio', models.CharField(max_length=100)),
                ('correo_personal', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=20, verbose_name='Celular / Teléfono')),
                ('correo_corporativo', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono_oficina', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_ingreso', models.DateField()),
                ('estado_empleado', models.CharField(default='ACTIVO', max_length=20)),
                ('tipo_contrato', models.CharField(choices=[('INDEFINIDO', 'Indefinido'), ('FIJO', 'Término Fijo'), ('OBRA_LABOR', 'Obra o Labor'), ('APRENDIZ_SENA', 'Aprendizaje SENA'), ('PRACTICANTE', 'Practicante Universitario'), ('PRESTACION_SERVICIOS', 'Prestación de Servicios')], default='INDEFINIDO', max_length=30)),
                ('termino_contrato', models.DateField(blank=True, help_text='Fecha fin de contrato si aplica', null=True)),
                ('salario', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('auxilio_transporte', models.BooleanField(default=True, help_text='¿Recibe auxilio de transporte legal?')),
                ('banco', models.CharField(choices=[('BANCOLOMBIA', 'Bancolombia'), ('DAVIVIENDA', 'Davivienda'), ('BBVA', 'BBVA'), ('BOGOTA', 'Banco de Bogotá'), ('OCCIDENTE', 'Banco de Occidente'), ('AV_VILLAS', 'Banco AV Villas'), ('NEQUI', 'Nequi'), ('DAVIPLATA', 'Daviplata')], max_length=50)),
                ('tipo_cuenta', models.CharField(choices=[('AHORROS', 'Ahorros'), ('CORRIENTE', 'Corriente')], default='AHORROS', max_length=20)),
                ('numero_cuenta', models.CharField(max_length=50)),
                ('eps', models.CharField(choices=[('SURA', 'EPS Sura'), ('SANITAS', 'Sanitas'), ('NUEVA_EPS', 'Nueva EPS'), ('SALUD_TOTAL', 'Salud Total'), ('COOMEVA', 'Coomeva'), ('FAMISANAR', 'Famisanar'), ('COMPENSAR', 'Compensar'), ('ALIANSALUD', 'Aliansalud'), ('NO_APLICA', 'No Aplica')], max_length=50)),
                ('fondo_pensiones', models.CharField(choices=[('PROTECCION', 'Protección'), ('PORVENIR', 'Porvenir'), ('COLFONDOS', 'Colfondos'), ('SKANDIA', 'Skandia'), ('COLPENSIONES', 'Colpensiones'), ('NO_APLICA', 'No Aplica')], max_length=50)),
                ('fondo_cesantias', models.CharField(choices=[('PROTECCION', 'Protección'), ('PORVENIR', 'Porvenir'), ('COLFONDOS', 'Colfondos'), ('FNA', 'Fondo Nacional del Ahorro'), ('NO_APLICA', 'No Aplica')], max_length=50)),
                ('dias_vacaciones', models.CharField(choices=[('L-V', 'Lunes a Viernes (Sábado NO hábil)'), ('L-S', 'Lunes a Sábado (Sábado hábil)')], default='L-V', help_text='Define si el sábado cuenta como hábil', max_length=5)),
                ('fecha_desvinculacion', models.DateField(blank=True, null=True)),
                ('motivo_retiro', models.CharField(blank=True, choices=[('RENUNCIA_VOLUNTARIA', 'Renuncia voluntaria'), ('TERMINACION_OBRA', 'Terminación obra o labor'), ('TERMINACION_JUSTA_CAUSA', 'Terminación de contrato con justa causa'), ('MUTUO_ACUERDO', 'Mutuo acuerdo'), ('VENCIMIENTO_TERMINO_FIJO', 'Vencimiento contrato fijo'), ('TERMINACION_APRENDIZAJE', 'Terminación contrato de aprendizaje'), ('MUERTE', 'Muerte del trabajador'), ('PERIODO_PRUEBA', 'Terminación del contrato por periodo de prueba'), ('ABANDONO_CARGO', 'Abandono de cargo'), ('SIN_JUSTA_CAUSA', 'Terminación de contrato sin justa causa')], max_length=50, null=True)),
                ('cargo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.cargo')),
                ('jefe_inmediato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinados', to='users.colaborador')),
                ('user', models.OneToOneField(blank=True, help_text='Usuario del sistema vinculado al colaborador', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sede', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.sede')),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('gerencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='users.gerencia')),
            ],
        ),
        migrations.CreateModel(
            name='SubArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo_centro_costos', models.CharField(help_text='Código contable del Centro de Costos', max_length=20, unique=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subareas', to='users.area')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalColaborador',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('TI', 'Tarjeta de Identidad'), ('PAS', 'Pasaporte'), ('PEP', 'Permiso Especial de Permanencia'), ('PPT', 'Permiso por Protección Temporal'), ('OTRO', 'Otro')], default='CC', max_length=10)),
                ('cedula', models.CharField(db_index=True, max_length=20, verbose_name='Número de Documento')),
                ('primer_apellido', models.CharField(max_length=50)),
                ('segundo_apellido', models.CharField(blank=True, max_length=50, null=True)),
                ('primer_nombre', models.CharField(max_length=50)),
                ('segundo_nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('fecha_nacimiento', models.DateField()),
                ('nacionalidad', models.CharField(default='Colombiana', max_length=50)),
                ('estado_civil', models.CharField(choices=[('SOLTERO', 'Soltero(a)'), ('CASADO', 'Casado(a)'), ('UNION_LIBRE', 'Unión Libre'), ('SEPARADO', 'Separado(a)'), ('DIVORCIADO', 'Divorciado(a)'), ('VIUDO', 'Viudo(a)')], default='SOLTERO', max_length=20)),
                ('direccion', models.CharField(max_length=200)),
                ('departamento', models.CharField(max_length=100)),
                ('municipio', models.CharField(max_length=100)),
                ('correo_personal', models.EmailField(db_index=True, max_length=254)),
                ('telefono', models.CharField(max_length=20, verbose_name='Celular / Teléfono')),
                ('correo_corporativo', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono_oficina', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_ingreso', models.DateField()),
                ('estado_empleado', models.CharField(default='ACTIVO', max_length=20)),
                ('tipo_contrato', models.CharField(choices=[('INDEFINIDO', 'Indefinido'), ('FIJO', 'Término Fijo'), ('OBRA_LABOR', 'Obra o Labor'), ('APRENDIZ_SENA', 'Aprendizaje SENA'), ('PRACTICANTE', 'Practicante Universitario'), ('PRESTACION_SERVICIOS', 'Prestación de Servicios')], default='INDEFINIDO', max_length=30)),
                ('termino_contrato', models.DateField(blank=True, help_text='Fecha fin de contrato si aplica', null=True)),
                ('salario', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('auxilio_transporte', models.BooleanField(default=True, help_text='¿Recibe auxilio de transporte legal?')),
                ('banco', models.CharField(choices=[('BANCOLOMBIA', 'Bancolombia'), ('DAVIVIENDA', 'Davivienda'), ('BBVA', 'BBVA'), ('BOGOTA', 'Banco de Bogotá'), ('OCCIDENTE', 'Banco de Occidente'), ('AV_VILLAS', 'Banco AV Villas'), ('NEQUI', 'Nequi'), ('DAVIPLATA', 'Daviplata')], max_length=50)),
                ('tipo_cuenta', models.CharField(choices=[('AHORROS', 'Ahorros'), ('CORRIENTE', 'Corriente')], default='AHORROS', max_length=20)),
                ('numero_cuenta', models.CharField(max_length=50)),
                ('eps', models.CharField(choices=[('SURA', 'EPS Sura'), ('SANITAS', 'Sanitas'), ('NUEVA_EPS', 'Nueva EPS'), ('SALUD_TOTAL', 'Salud Total'), ('COOMEVA', 'Coomeva'), ('FAMISANAR', 'Famisanar'), ('COMPENSAR', 'Compensar'), ('ALIANSALUD', 'Aliansalud'), ('NO_APLICA', 'No Aplica')], max_length=50)),
                ('fondo_pensiones', models.CharField(choices=[('PROTECCION', 'Protección'), ('PORVENIR', 'Porvenir'), ('COLFONDOS', 'Colfondos'), ('SKANDIA', 'Skandia'), ('COLPENSIONES', 'Colpensiones'), ('NO_APLICA', 'No Aplica')], max_length=50)),
                ('fondo_cesantias', models.CharField(choices=[('PROTECCION', 'Protección'), ('PORVENIR', 'Porvenir'), ('COLFONDOS', 'Colfondos'), ('FNA', 'Fondo Nacional del Ahorro'), ('NO_APLICA', 'No Aplica')], max_length=50)),
                ('dias_vacaciones', models.CharField(choices=[('L-V', 'Lunes a Viernes (Sábado NO hábil)'), ('L-S', 'Lunes a Sábado (Sábado hábil)')], default='L-V', help_text='Define si el sábado cuenta como hábil', max_length=5)),
                ('fecha_desvinculacion', models.DateField(blank=True, null=True)),
                ('motivo_retiro', models.CharField(blank=True, choices=[('RENUNCIA_VOLUNTARIA', 'Renuncia voluntaria'), ('TERMINACION_OBRA', 'Terminación obra o labor'), ('TERMINACION_JUSTA_CAUSA', 'Terminación de contrato con justa causa'), ('MUTUO_ACUERDO', 'Mutuo acuerdo'), ('VENCIMIENTO_TERMINO_FIJO', 'Vencimiento contrato fijo'), ('TERMINACION_APRENDIZAJE', 'Terminación contrato de aprendizaje'), ('MUERTE', 'Muerte del trabajador'), ('PERIODO_PRUEBA', 'Terminación del contrato por periodo de prueba'), ('ABANDONO_CARGO', 'Abandono de cargo'), ('SIN_JUSTA_CAUSA', 'Terminación de contrato sin justa causa')], max_length=50, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('cargo', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.cargo')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('jefe_inmediato', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.colaborador')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, help_text='Usuario del sistema vinculado al colaborador', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sede', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.sede')),
                ('sub_area', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.subarea', verbose_name='Centro de Costos')),
            ],
            options={
                'verbose_name': 'historical colaborador',
                'verbose_name_plural': 'historical colaboradors',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='sub_area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.subarea', verbose_name='Centro de Costos'),
        ),
    ]
