# Generated by Django 5.2.5 on 2026-01-24 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='areas',
            field=models.ManyToManyField(blank=True, help_text='Áreas a las que pertenece este cargo', related_name='cargos', to='users.area'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='nivel_jerarquico',
            field=models.CharField(choices=[('ESTRATEGICO', 'Estratégico'), ('TACTICO', 'Táctico'), ('OPERATIVO', 'Operativo')], default='OPERATIVO', max_length=50),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
