# Generated by Django 5.2.5 on 2026-01-25 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_cargo_areas_alter_cargo_nivel_jerarquico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='numero_contrato',
            field=models.PositiveIntegerField(default=1, verbose_name='Número de Contrato Actual'),
        ),
        migrations.AddField(
            model_name='historicalcolaborador',
            name='numero_contrato',
            field=models.PositiveIntegerField(default=1, verbose_name='Número de Contrato Actual'),
        ),
        migrations.CreateModel(
            name='HistoricoContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de Finalización')),
                ('motivo_retiro', models.CharField(blank=True, max_length=255, null=True)),
                ('cargo_snapshot', models.CharField(blank=True, max_length=255, null=True)),
                ('gerencia_snapshot', models.CharField(blank=True, max_length=255, null=True)),
                ('area_snapshot', models.CharField(blank=True, max_length=255, null=True)),
                ('sede_snapshot', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos_previos', to='users.colaborador')),
            ],
        ),
    ]
