# Generated by Django 5.2.5 on 2026-02-13 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_colaborador_numero_contrato_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.cargo', verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='fecha_ingreso',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Ingreso'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='tipo_contrato',
            field=models.CharField(blank=True, choices=[('INDEFINIDO', 'Indefinido'), ('FIJO', 'Término Fijo'), ('OBRA_LABOR', 'Obra o Labor'), ('APRENDIZ_SENA', 'Aprendizaje SENA'), ('PRACTICANTE', 'Practicante Universitario'), ('PRESTACION_SERVICIOS', 'Prestación de Servicios')], default='INDEFINIDO', max_length=30, null=True, verbose_name='Tipo de Contrato'),
        ),
        migrations.AlterField(
            model_name='historicalcolaborador',
            name='cargo',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.cargo', verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='historicalcolaborador',
            name='fecha_ingreso',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Ingreso'),
        ),
        migrations.AlterField(
            model_name='historicalcolaborador',
            name='tipo_contrato',
            field=models.CharField(blank=True, choices=[('INDEFINIDO', 'Indefinido'), ('FIJO', 'Término Fijo'), ('OBRA_LABOR', 'Obra o Labor'), ('APRENDIZ_SENA', 'Aprendizaje SENA'), ('PRACTICANTE', 'Practicante Universitario'), ('PRESTACION_SERVICIOS', 'Prestación de Servicios')], default='INDEFINIDO', max_length=30, null=True, verbose_name='Tipo de Contrato'),
        ),
    ]
