# Generated by Django 5.2.5 on 2026-01-18 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_colaborador_user_historicalcolaborador_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='motivo_retiro',
            field=models.CharField(blank=True, choices=[('RENUNCIA_VOLUNTARIA', 'Renuncia voluntaria'), ('TERMINACION_OBRA', 'Terminación obra o labor'), ('TERMINACION_JUSTA_CAUSA', 'Terminación de contrato con justa causa'), ('MUTUO_ACUERDO', 'Mutuo acuerdo'), ('VENCIMIENTO_TERMINO_FIJO', 'Vencimiento contrato fijo'), ('TERMINACION_APRENDIZAJE', 'Terminación contrato de aprendizaje'), ('MUERTE', 'Muerte del trabajador'), ('PERIODO_PRUEBA', 'Terminación del contrato por periodo de prueba'), ('ABANDONO_CARGO', 'Abandono de cargo'), ('SIN_JUSTA_CAUSA', 'Terminación de contrato sin justa causa')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalcolaborador',
            name='motivo_retiro',
            field=models.CharField(blank=True, choices=[('RENUNCIA_VOLUNTARIA', 'Renuncia voluntaria'), ('TERMINACION_OBRA', 'Terminación obra o labor'), ('TERMINACION_JUSTA_CAUSA', 'Terminación de contrato con justa causa'), ('MUTUO_ACUERDO', 'Mutuo acuerdo'), ('VENCIMIENTO_TERMINO_FIJO', 'Vencimiento contrato fijo'), ('TERMINACION_APRENDIZAJE', 'Terminación contrato de aprendizaje'), ('MUERTE', 'Muerte del trabajador'), ('PERIODO_PRUEBA', 'Terminación del contrato por periodo de prueba'), ('ABANDONO_CARGO', 'Abandono de cargo'), ('SIN_JUSTA_CAUSA', 'Terminación de contrato sin justa causa')], max_length=50, null=True),
        ),
    ]
